# Generated by Django 5.1.5 on 2025-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', help_text='Categoria (Buzos, Pantalones, Remeras, etc.) EN PLURAL', max_length=255, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors_available',
            field=models.CharField(help_text='Lista de colores disponibles separados por comas, por ejemplo: Rojo, Azul, Verde', max_length=255, verbose_name='Colores disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes_available',
            field=models.CharField(help_text='Lista de talles disponibles separados por comas, por ejemplo: S, M, L', max_length=255, verbose_name='Talles disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
