# Generated by Django 5.1.5 on 2025-02-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_alter_product_colors_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Activalo para destacar el producto (va a aparecer en la pagina principal como producto destacado)', verbose_name='Destacar producto'),
        ),
    ]
